@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package mod.traister101.sacks.common.capability;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;